CREATE TABLE faculty (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lastName VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  middleName VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  employeeCode INT NOT NULL,
  school VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  program VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);